### PR TITLE
Fixed signatures crashing.

### PR DESCRIPTION
**Pull request by gir489returns**
image

### CODE REVIEW

**Comment by gir489returns** [comment]
Show All Map Icons is crashing when you open the map.

**Comment by gir489returns** [comment]
Should be fine now.

**Comment by rogeriocamorim** [comment]
> Show All Map Icons is crashing when you open the map.

Maybe remove that for now ?

**Comment by gir489returns** [comment]
> > Show All Map Icons is crashing when you open the map.
> 
> Maybe remove that for now ?

I fixed it.

**Comment by xicemanx117** [comment]
so how do i go about adding this to the master to compile the .dll?

**Comment by gir489returns** [comment]
> so how do i go about adding this to the master to compile the .dll?

You can either pull my branch, or just download dllmain.cpp and copy it over.

**Comment by m44v** [comment]
Pulled your branch and compiled. Doesn't open and just crashes for me.

**Comment by xicemanx117** [comment]
> > so how do i go about adding this to the master to compile the .dll?
> 
> You can either pull my branch, or just download dllmain.cpp and copy it over.

it crashed like the master did after i pulled and compiled

**Comment by xicemanx117** [comment]
> > so how do i go about adding this to the master to compile the .dll?
> 
> You can either pull my branch, or just download dllmain.cpp and copy it over.

and i get this error when i download the dllmain.cpp and try to compile.............. Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	C1083	Cannot open include file: 'version.h': No such file or directory	version

**Comment by rogeriocamorim** [comment]
work fine i just tested

**Comment by xicemanx117** [comment]
> work fine i just tested

i guess ill just wait for the released .dll cause im an idiot and have no idea what im doing.... but its awesome its working for ya... what do you click to compile?

**Pull request merged**
