### PR TITLE
bypass AC

### PR DESCRIPTION
**Pull request by Sinnisterly**
removed title and print functions to bypass AC.

### CODE REVIEW

**Comment by g020276j** [comment]
I made a PR for this too, I removed any reference to 'Cheat' in the console too

**Comment by RinTheWeeb** [comment]
xor strings should do the trick just fine

**Comment by emoisback** [comment]
ill add XorString instead then

**Comment by gir489returns** [comment]
> xor strings should do the trick just fine

That is easily detected too, they can see what we're doing then just detect it. If I was the gooks, that would be my next move to stop this. I think instead we should just have it use some kind of config loader that doesn't use strings, like a Blake2B hashed INI or something.

**Comment by emoisback** [comment]
> > xor strings should do the trick just fine
> 
> That is easily detected too, they can see what we're doing then just detect it. If I was the gooks, that would be my next move to stop this. I think instead we should just have it use some kind of config loader that doesn't use strings, like a Blake2B hashed INI or something.

will look into it..

for now i will add xor so it can be used for a while..

**Pull request closed without merging**
